Repository PatientPaI/backend, pull requests merged in 2024-06, with the labels that each got.

#43 Ci: 변경사항 발생 시 빌드 후 배포하는 자동화 파이프라인 구성
  .github/workflows/build-and-deploy.yml
Labels: 🏗️ infrastructure

#39 Feat: Matching 관련 Create, Read, Cancel, Accept 기능 구현
  src/main/java/com/patientpal/backend/common/exception/ErrorCode.java
  src/main/java/com/patientpal/backend/matching/application/MatchService.java
  src/main/java/com/patientpal/backend/matching/application/MatchServiceImpl.java
  src/main/java/com/patientpal/backend/matching/application/MatchValidation.java
  src/main/java/com/patientpal/backend/matching/domain/FirstRequest.java
  src/main/java/com/patientpal/backend/matching/domain/Match.java
  src/main/java/com/patientpal/backend/matching/domain/MatchRepository.java
  src/main/java/com/patientpal/backend/matching/domain/MatchStatus.java
  src/main/java/com/patientpal/backend/matching/domain/ReadStatus.java
  src/main/java/com/patientpal/backend/matching/dto/response/CreateMatchResponse.java
  src/main/java/com/patientpal/backend/matching/dto/response/MatchListResponse.java
  src/main/java/com/patientpal/backend/matching/dto/response/MatchResponse.java
  src/main/java/com/patientpal/backend/matching/exception/CanNotReadException.java
  src/main/java/com/patientpal/backend/matching/exception/CanNotRequestException.java
  src/main/java/com/patientpal/backend/matching/exception/DuplicateRequestException.java
  src/main/java/com/patientpal/backend/matching/exception/NotCompleteProfileException.java
  src/main/java/com/patientpal/backend/matching/presentation/MatchController.java
  src/main/java/com/patientpal/backend/member/domain/Caregiver.java
  src/main/java/com/patientpal/backend/member/domain/CaregiverRepository.java
  src/main/java/com/patientpal/backend/member/domain/Member.java
  src/main/java/com/patientpal/backend/member/domain/Patient.java
  src/main/java/com/patientpal/backend/member/domain/PatientRepository.java
  src/main/java/com/patientpal/backend/member/service/MemberService.java
Labels: 👀 review

#48 Feat/notice create authentication
  src/main/java/com/patientpal/backend/member/service/MemberService.java
  src/main/java/com/patientpal/backend/post/controller/NoticeController.java
  src/main/java/com/patientpal/backend/post/service/PostService.java
Labels: ✨ feature, 👀 review

#53 Feat: Roletype custom annotation 구현 후 적용
  src/main/java/com/patientpal/backend/config/InterceptorConfig.java
  src/main/java/com/patientpal/backend/post/controller/NoticeController.java
  src/main/java/com/patientpal/backend/post/libs/RoleInterceptor.java
  src/main/java/com/patientpal/backend/post/libs/RoleType.java
Labels: ✨ feature, 👀 review

#57 Rename: 성격이 비슷한 두 패키지를 병합함
  src/main/java/com/patientpal/backend/common/controller/PingController.java
  src/main/java/com/patientpal/backend/config/config/JpaAuditingConfig.java
Labels: 🛠️ refactor

#59 Config: 운영 환경에서 스키마를 검증하지 않도록 변경함
  src/main/resources/application.yml
Labels: 🐞 bug

#61 Fix: 운영 서버에서 prod 프로필을 사용하도록 Docker 설정 수정
  .github/workflows/build-and-deploy.yml
  Dockerfile
Labels: 🐞 bug, 🏗️ infrastructure

#64 Feat: 컨트롤러 슬라이스 테스트에 사용되는 공통 클래스 정의
  build.gradle
  src/test/java/com/patientpal/backend/BackendApplicationTests.java
  src/test/java/com/patientpal/backend/test/CommonControllerSliceTest.java
  src/test/java/com/patientpal/backend/test/annotation/AutoServiceMockBeans.java
  src/test/java/com/patientpal/backend/test/annotation/ServiceMockBeanRegistrar.java
Labels: ✨ feature, 🔗 dependencies

#71 Ci: Reviewdog를 통해서 PR 시 구글 자바 컨벤션 검사
  .github/custom_google_checks.xml
  .github/workflows/build_and_deploy.yml
  .github/workflows/review_checkstyle.yml
Labels: 🏗️ infrastructure

#72 Feat: 스네이크 케이스로 작성된 테스트 클래스명이나 메서드명을 통해 `@DisplayName`을 자동으로 달게함
  src/test/java/com/patientpal/backend/test/annotation/AutoKoreanDisplayName.java
Labels: ✨ feature

#74 Refactor: 테이블 명을 복수형으로 통일함
  src/main/java/com/patientpal/backend/auth/domain/RefreshToken.java
  src/main/java/com/patientpal/backend/caregiver/domain/Caregiver.java
  src/main/java/com/patientpal/backend/matching/domain/Match.java
  src/main/java/com/patientpal/backend/member/domain/Member.java
  src/main/java/com/patientpal/backend/patient/domain/Patient.java
  src/main/java/com/patientpal/backend/post/domain/Post.java
Labels: 🛠️ refactor

#77 Fix: 한글 테스트 메서드 명을 위해 메서드 네이밍 컨벤션을 완화함
  .github/auto_assign_config.yml
  .github/custom_google_checks.xml
Labels: 🐞 bug, 📚 documentation, 🏗️ infrastructure

#76 Fix: 보안 상의 문제로 리프레시 토큰은 HTTP-Only 쿠키를 통해 전달하도록 수정함
  .editorconfig
  .github/custom_google_checks.xml
  src/main/java/com/patientpal/backend/auth/controller/AuthenticationApiV1Controller.java
  src/main/java/com/patientpal/backend/auth/dto/AccessTokenResponse.java
  src/main/java/com/patientpal/backend/auth/dto/RefreshTokenRequest.java
  src/main/java/com/patientpal/backend/auth/dto/SignInRequest.java
  src/main/java/com/patientpal/backend/auth/dto/TokenDto.java
  src/main/java/com/patientpal/backend/auth/dto/TokenResponse.java
  src/main/java/com/patientpal/backend/auth/service/JwtLoginService.java
  src/main/java/com/patientpal/backend/auth/service/JwtTokenService.java
  src/main/java/com/patientpal/backend/auth/service/RefreshTokenService.java
  src/test/java/com/patientpal/backend/auth/controller/AuthenticationApiV1ControllerTest.java
  src/test/java/com/patientpal/backend/auth/service/JwtLoginServiceTest.java
  src/test/java/com/patientpal/backend/auth/service/JwtTokenServiceTest.java
  src/test/java/com/patientpal/backend/auth/service/LoginServiceTest.java
  src/test/java/com/patientpal/backend/auth/service/RefreshTokenServiceTest.java
  src/test/java/com/patientpal/backend/common/validation/FieldMatchValidatorTest.java
  src/test/java/com/patientpal/backend/fixtures/auth/AccessTokenResponseFixture.java
  src/test/java/com/patientpal/backend/fixtures/auth/RefreshTokenFixture.java
  src/test/java/com/patientpal/backend/fixtures/auth/SignInRequestFixture.java
  src/test/java/com/patientpal/backend/fixtures/auth/SignUpRequestFixture.java
  src/test/java/com/patientpal/backend/fixtures/auth/TokenDtoFixture.java
  src/test/java/com/patientpal/backend/fixtures/member/MemberFixture.java
  src/test/java/com/patientpal/backend/fixtures/member/SignUpRequestFixture.java
Labels: 📚 documentation, 🔄 API, 🔒 security

#70 Feat: Patient, Caregiver 프로필 Controller, Service 모든 메서드를 테스트함 (중복 등록, 삭제 제외)
  .github/custom_google_checks.xml
  .github/workflows/review_checkstyle.yml
  src/main/java/com/patientpal/backend/caregiver/dto/request/CaregiverProfileCreateRequest.java
  src/main/java/com/patientpal/backend/caregiver/dto/request/CaregiverProfileUpdateRequest.java
  src/main/java/com/patientpal/backend/patient/dto/request/PatientProfileCreateRequest.java
  src/main/java/com/patientpal/backend/patient/dto/request/PatientProfileUpdateRequest.java
  src/test/java/com/patientpal/backend/caregiver/controller/CaregiverControllerV1Test.java
  src/test/java/com/patientpal/backend/caregiver/service/CaregiverServiceTest.java
  src/test/java/com/patientpal/backend/fixtures/caregiver/CaregiverFixture.java
  src/test/java/com/patientpal/backend/fixtures/member/MemberFixture.java
  src/test/java/com/patientpal/backend/fixtures/patient/PatientFixture.java
  src/test/java/com/patientpal/backend/patient/controller/PatientControllerV1Test.java
  src/test/java/com/patientpal/backend/patient/service/PatientServiceTest.java
  src/test/java/com/patientpal/backend/test/annotation/WithCustomMockUserCaregiver.java
  src/test/java/com/patientpal/backend/test/annotation/WithCustomMockUserPatient.java
Labels: ✨ feature

#80 Doc: 편의를 위해 이슈 카테고리를 세분화함
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/deployment.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/environment.yml
  .github/ISSUE_TEMPLATE/meeting.yml
  .github/ISSUE_TEMPLATE/new_feature.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/ISSUE_TEMPLATE/testing.yml
Labels: 📚 문서화

#82 Feat: 프로필, 매칭 관련 TODO 진행함
  src/main/java/com/patientpal/backend/caregiver/controller/CaregiverControllerV1.java
  src/main/java/com/patientpal/backend/caregiver/domain/Caregiver.java
  src/main/java/com/patientpal/backend/caregiver/dto/request/CaregiverProfileCreateRequest.java
  src/main/java/com/patientpal/backend/caregiver/dto/response/CaregiverProfileResponse.java
  src/main/java/com/patientpal/backend/caregiver/service/CaregiverService.java
  src/main/java/com/patientpal/backend/common/exception/ErrorCode.java
  src/main/java/com/patientpal/backend/matching/controller/MatchController.java
  src/main/java/com/patientpal/backend/matching/domain/MatchRepository.java
  src/main/java/com/patientpal/backend/matching/domain/MatchStatus.java
  src/main/java/com/patientpal/backend/matching/dto/response/CreateMatchResponse.java
  src/main/java/com/patientpal/backend/matching/dto/response/MatchResponse.java
  src/main/java/com/patientpal/backend/matching/exception/CanNotAcceptException.java
  src/main/java/com/patientpal/backend/matching/exception/CanNotDeleteException.java
  src/main/java/com/patientpal/backend/matching/service/MatchService.java
  src/main/java/com/patientpal/backend/matching/service/MatchServiceImpl.java
  src/main/java/com/patientpal/backend/matching/service/MatchValidation.java
  src/main/java/com/patientpal/backend/patient/controller/PatientControllerV1.java
  src/main/java/com/patientpal/backend/patient/domain/Patient.java
  src/main/java/com/patientpal/backend/patient/dto/request/PatientProfileCreateRequest.java
  src/main/java/com/patientpal/backend/patient/dto/response/PatientProfileResponse.java
  src/main/java/com/patientpal/backend/patient/service/PatientService.java
Labels: ✨ 기능

#83 Feat: 운영 서버에서 비정상 예외 발생 시 웹훅을 통해 디스코드 채널로 전달하도록 함
  src/main/java/com/patientpal/backend/common/advice/RestApiExceptionHandler.java
  src/main/java/com/patientpal/backend/webhook/dto/DiscordMessage.java
  src/main/java/com/patientpal/backend/webhook/service/DiscordWebhookService.java
  src/main/resources/application.yml
Labels: ✨ 기능

#86 Fix: 삭제 관련 테스트 실패 문제 해결
  src/test/java/com/patientpal/backend/caregiver/service/CaregiverServiceTest.java
  src/test/java/com/patientpal/backend/patient/service/PatientServiceTest.java
Labels: 🧪 테스트

#89 Feat: AWS S3, presigned url을 이용한 이미지 등록 기능, 테스트 구현함
  build.gradle
  src/main/java/com/patientpal/backend/caregiver/controller/CaregiverControllerV1.java
  src/main/java/com/patientpal/backend/caregiver/domain/Caregiver.java
  src/main/java/com/patientpal/backend/caregiver/dto/request/CaregiverProfileCreateRequest.java
  src/main/java/com/patientpal/backend/caregiver/dto/response/CaregiverProfileResponse.java
  src/main/java/com/patientpal/backend/caregiver/service/CaregiverService.java
  src/main/java/com/patientpal/backend/config/S3Config.java
  src/main/java/com/patientpal/backend/image/dto/ImageNameDto.java
  src/main/java/com/patientpal/backend/image/service/PresignedUrlService.java
  src/main/java/com/patientpal/backend/patient/controller/PatientControllerV1.java
  src/main/java/com/patientpal/backend/patient/domain/Patient.java
  src/main/java/com/patientpal/backend/patient/dto/request/PatientProfileCreateRequest.java
  src/main/java/com/patientpal/backend/patient/dto/response/PatientProfileResponse.java
  src/main/java/com/patientpal/backend/patient/service/PatientService.java
  src/main/resources/application.yml
  src/test/java/com/patientpal/backend/caregiver/controller/CaregiverControllerV1Test.java
  src/test/java/com/patientpal/backend/caregiver/service/CaregiverServiceTest.java
  src/test/java/com/patientpal/backend/fixtures/image/ImageFixture.java
  src/test/java/com/patientpal/backend/image/service/PresignedUrlServiceTest.java
  src/test/java/com/patientpal/backend/patient/controller/PatientControllerV1Test.java
  src/test/java/com/patientpal/backend/patient/service/PatientServiceTest.java
Labels: 📚 문서화, ✨ 기능, 🧪 테스트

#90 Config: Jasypt 암호화 키 변경
  src/main/resources/application.yml
Labels: 🐞 버그, 🔒 보안, 🛠️ 리팩터링, 🛠️ 설정

#98 Feat: @RoleType 어노테이션 반복 사용 기능 추가
  src/main/java/com/patientpal/backend/post/libs/RoleType.java
  src/main/java/com/patientpal/backend/post/libs/RoleTypes.java
Labels: ✨ 기능

#96 Feat: 환자 -> 간병인 찾기, 간병인 -> 환자 찾기 기능 추가
  .gitignore
  build.gradle
  src/main/java/com/patientpal/backend/caregiver/controller/CaregiverControllerV1.java
  src/main/java/com/patientpal/backend/caregiver/domain/Caregiver.java
  src/main/java/com/patientpal/backend/caregiver/dto/request/CaregiverProfileCreateRequest.java
  src/main/java/com/patientpal/backend/caregiver/dto/response/CaregiverProfileDetailResponse.java
  src/main/java/com/patientpal/backend/caregiver/dto/response/CaregiverProfileListResponse.java
  src/main/java/com/patientpal/backend/caregiver/dto/response/CaregiverProfileResponse.java
  src/main/java/com/patientpal/backend/caregiver/repository/CaregiverProfileSearchRepositoryCustom.java
  src/main/java/com/patientpal/backend/caregiver/repository/CaregiverRepository.java
  src/main/java/com/patientpal/backend/caregiver/repository/CaregiverRepositoryImpl.java
  src/main/java/com/patientpal/backend/caregiver/service/CaregiverService.java
  src/main/java/com/patientpal/backend/common/exception/ErrorCode.java
  src/main/java/com/patientpal/backend/common/querydsl/ProfileSearchCondition.java
  src/main/java/com/patientpal/backend/member/domain/Address.java
  src/main/java/com/patientpal/backend/patient/controller/PatientControllerV1.java
  src/main/java/com/patientpal/backend/patient/domain/Patient.java
  src/main/java/com/patientpal/backend/patient/dto/request/PatientProfileCreateRequest.java
  src/main/java/com/patientpal/backend/patient/dto/response/PatientProfileDetailResponse.java
  src/main/java/com/patientpal/backend/patient/dto/response/PatientProfileListResponse.java
  src/main/java/com/patientpal/backend/patient/dto/response/PatientProfileResponse.java
  src/main/java/com/patientpal/backend/patient/repository/PatientProfileSearchRepositoryCustom.java
  src/main/java/com/patientpal/backend/patient/repository/PatientRepository.java
  src/main/java/com/patientpal/backend/patient/repository/PatientRepositoryImpl.java
  src/main/java/com/patientpal/backend/patient/service/PatientService.java
  src/test/java/com/patientpal/backend/caregiver/controller/CaregiverControllerV1Test.java
  src/test/java/com/patientpal/backend/caregiver/service/CaregiverServiceTest.java
  src/test/java/com/patientpal/backend/fixtures/caregiver/CaregiverFixture.java
  src/test/java/com/patientpal/backend/fixtures/patient/PatientFixture.java
  src/test/java/com/patientpal/backend/patient/controller/PatientControllerV1Test.java
  src/test/java/com/patientpal/backend/patient/service/PatientServiceTest.java
Labels: 📚 문서화, ✨ 기능, 🔗 의존성

#100 Feat: 매칭 서비스 테스트 추가
  src/main/java/com/patientpal/backend/matching/controller/MatchController.java
  src/main/java/com/patientpal/backend/matching/service/MatchService.java
  src/main/java/com/patientpal/backend/matching/service/MatchServiceImpl.java
  src/main/java/com/patientpal/backend/member/domain/Member.java
  src/test/java/com/patientpal/backend/fixtures/caregiver/CaregiverFixture.java
  src/test/java/com/patientpal/backend/fixtures/match/MatchFixture.java
  src/test/java/com/patientpal/backend/fixtures/patient/PatientFixture.java
  src/test/java/com/patientpal/backend/matching/controller/MatchControllerTest.java
  src/test/java/com/patientpal/backend/matching/service/CaregiverMatchServiceTest.java
  src/test/java/com/patientpal/backend/matching/service/PatientMatchServiceTest.java
Labels: 🧪 테스트

#104 Config: CorsFilter 추가
  src/main/java/com/patientpal/backend/config/SecurityConfig.java
Labels: 🔒 보안, 🛠️ 설정

#102 Feat: 소셜 로그인 기능 구현
  .github/workflows/review_checkstyle.yml
  build.gradle
  src/main/java/com/patientpal/backend/common/exception/ErrorCode.java
  src/main/java/com/patientpal/backend/common/utils/ConvertUtils.java
  src/main/java/com/patientpal/backend/config/JpaAuditingConfig.java
  src/main/java/com/patientpal/backend/config/SecurityConfig.java
  src/main/java/com/patientpal/backend/member/domain/Member.java
  src/main/java/com/patientpal/backend/security/oauth/CustomOauth2UserPrincipal.java
  src/main/java/com/patientpal/backend/security/oauth/CustomOauth2UserService.java
  src/main/java/com/patientpal/backend/security/oauth/userinfo/CustomOauth2Provider.java
  src/main/java/com/patientpal/backend/security/oauth/userinfo/CustomOauth2UserInfo.java
  src/main/java/com/patientpal/backend/security/oauth/userinfo/GoogleOauth2UserInfo.java
  src/main/java/com/patientpal/backend/security/oauth/userinfo/KakaoOauth2UserInfo.java
  src/main/java/com/patientpal/backend/security/oauth/userinfo/NaverOauth2UserInfo.java
  src/main/resources/application.yml
Labels: ✨ 기능

#112 Refactor: JPA 상속 매핑 (Join 전략)에 따라 엔티티를 수정하고 프로필, 매칭 관련 로직을 수정한다.
  src/main/java/com/patientpal/backend/auth/dto/SignUpRequest.java
  src/main/java/com/patientpal/backend/caregiver/controller/CaregiverControllerV1.java
  src/main/java/com/patientpal/backend/caregiver/domain/Caregiver.java
  src/main/java/com/patientpal/backend/caregiver/dto/request/CaregiverProfileCreateRequest.java
  src/main/java/com/patientpal/backend/caregiver/dto/response/CaregiverProfileDetailResponse.java
  src/main/java/com/patientpal/backend/caregiver/repository/CaregiverRepository.java
  src/main/java/com/patientpal/backend/caregiver/service/CaregiverService.java
  src/main/java/com/patientpal/backend/common/BaseTimeEntity.java
  src/main/java/com/patientpal/backend/common/exception/ErrorCode.java
  src/main/java/com/patientpal/backend/matching/controller/MatchController.java
  src/main/java/com/patientpal/backend/matching/domain/Match.java
  src/main/java/com/patientpal/backend/matching/domain/MatchRepository.java
  src/main/java/com/patientpal/backend/matching/dto/response/MatchResponse.java
  src/main/java/com/patientpal/backend/matching/service/MatchService.java
  src/main/java/com/patientpal/backend/matching/service/MatchServiceImpl.java
  src/main/java/com/patientpal/backend/matching/service/MatchValidation.java
  src/main/java/com/patientpal/backend/member/domain/Member.java
  src/main/java/com/patientpal/backend/member/service/MemberService.java
  src/main/java/com/patientpal/backend/patient/controller/PatientControllerV1.java
  src/main/java/com/patientpal/backend/patient/domain/Patient.java
  src/main/java/com/patientpal/backend/patient/dto/request/PatientProfileCreateRequest.java
  src/main/java/com/patientpal/backend/patient/dto/response/PatientProfileDetailResponse.java
  src/main/java/com/patientpal/backend/patient/repository/PatientRepository.java
  src/main/java/com/patientpal/backend/patient/service/PatientService.java
  src/main/java/com/patientpal/backend/post/libs/RoleInterceptor.java
Labels: ✨ 기능, 🛠️ 리팩터링

#107 Feat: 게시글 Update, Delete 함수 실행시 member 를 검사하도록 수정
  src/main/java/com/patientpal/backend/post/controller/BoardController.java
  src/main/java/com/patientpal/backend/post/controller/NoticeController.java
  src/main/java/com/patientpal/backend/post/service/PostService.java
Labels: ✨ 기능

#119 Test: 테이블 구조 변경에 따라 기존 테스트 수정
  src/main/java/com/patientpal/backend/caregiver/service/CaregiverService.java
  src/main/java/com/patientpal/backend/member/domain/Member.java
  src/main/java/com/patientpal/backend/patient/service/PatientService.java
  src/test/java/com/patientpal/backend/caregiver/controller/CaregiverControllerV1Test.java
  src/test/java/com/patientpal/backend/caregiver/service/CaregiverServiceTest.java
  src/test/java/com/patientpal/backend/fixtures/auth/SignUpRequestFixture.java
  src/test/java/com/patientpal/backend/fixtures/caregiver/CaregiverFixture.java
  src/test/java/com/patientpal/backend/fixtures/match/MatchFixture.java
  src/test/java/com/patientpal/backend/fixtures/member/MemberFixture.java
  src/test/java/com/patientpal/backend/fixtures/patient/PatientFixture.java
  src/test/java/com/patientpal/backend/matching/controller/MatchControllerTest.java
  src/test/java/com/patientpal/backend/matching/service/CaregiverMatchServiceTest.java
  src/test/java/com/patientpal/backend/matching/service/PatientMatchServiceTest.java
  src/test/java/com/patientpal/backend/patient/controller/PatientControllerV1Test.java
  src/test/java/com/patientpal/backend/patient/service/PatientServiceTest.java
Labels: 🧪 테스트

#121 Deployment: DOCKER를 사용해 CI/CD 진행
  .github/workflows/build_and_deploy.yml
Labels: ⚙️ 데브옵스
