Repository PatientPaI/backend, pull requests merged in 2024-05, with the labels that each got.

#4 [feat] Member 엔티티를 추가한다
  src/main/java/com/patientpal/backend/member/domain/Gender.java
  src/main/java/com/patientpal/backend/member/domain/Member.java
  src/main/java/com/patientpal/backend/member/domain/Provider.java
  src/main/java/com/patientpal/backend/member/domain/Role.java
Labels: 👀 review, 🟡 priority: medium

#15 Fix: 권한 문제로 인해 Auto assign action이 제대로 동작하지 않는 것을 수정함
  .github/workflows/auto_assign_action.yml
Labels: 🐞 bug

#20 Feat: Matching에 필요한 Patient, Caregiver, Match 엔티티 추가
  .gitignore
  build.gradle
  src/main/java/com/patientpal/backend/common/BaseEntity.java
  src/main/java/com/patientpal/backend/common/BaseTimeEntity.java
  src/main/java/com/patientpal/backend/matching/domain/Match.java
  src/main/java/com/patientpal/backend/matching/domain/MatchStatus.java
  src/main/java/com/patientpal/backend/member/domain/Address.java
  src/main/java/com/patientpal/backend/member/domain/Caregiver.java
  src/main/java/com/patientpal/backend/member/domain/Patient.java
  src/main/resources/application-local.yml
Labels: ✨ feature

#23 Remove: PostController Class 제거
  src/main/java/com/patientpal/backend/noticecommunity/controller/PostController.java
Labels: 🛠️ refactor

#27 Feat: Swagger 관련 세팅 추가
  build.gradle
  src/main/java/com/patientpal/backend/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: 🔗 dependencies

#26 Feat: JWT 인증을 통한 일반 로그인 추가
  build.gradle
  src/main/java/com/patientpal/backend/auth/controller/AuthenticationApiV1Controller.java
  src/main/java/com/patientpal/backend/auth/domain/RefreshToken.java
  src/main/java/com/patientpal/backend/auth/dto/RefreshTokenRequest.java
  src/main/java/com/patientpal/backend/auth/dto/SignInRequest.java
  src/main/java/com/patientpal/backend/auth/dto/SignUpRequest.java
  src/main/java/com/patientpal/backend/auth/dto/TokenResponse.java
  src/main/java/com/patientpal/backend/auth/repository/RefreshTokenRepository.java
  src/main/java/com/patientpal/backend/auth/service/JwtLoginService.java
  src/main/java/com/patientpal/backend/auth/service/JwtTokenService.java
  src/main/java/com/patientpal/backend/auth/service/LoginService.java
  src/main/java/com/patientpal/backend/auth/service/RefreshTokenService.java
  src/main/java/com/patientpal/backend/common/advice/RestApiExceptionHandler.java
  src/main/java/com/patientpal/backend/common/exception/AuthenticationException.java
  src/main/java/com/patientpal/backend/common/exception/AuthorizationException.java
  src/main/java/com/patientpal/backend/common/exception/BusinessException.java
  src/main/java/com/patientpal/backend/common/exception/EntityNotFoundException.java
  src/main/java/com/patientpal/backend/common/exception/ErrorCode.java
  src/main/java/com/patientpal/backend/common/exception/ErrorResponse.java
  src/main/java/com/patientpal/backend/common/exception/InvalidValueException.java
  src/main/java/com/patientpal/backend/config/SecurityConfig.java
  src/main/java/com/patientpal/backend/member/domain/Member.java
  src/main/java/com/patientpal/backend/member/dto/MemberResponse.java
  src/main/java/com/patientpal/backend/member/repository/MemberRepository.java
  src/main/java/com/patientpal/backend/member/service/MemberService.java
  src/main/java/com/patientpal/backend/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/patientpal/backend/security/jwt/JwtAuthTokenFilter.java
  src/main/java/com/patientpal/backend/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/patientpal/backend/security/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: ✨ feature, 👀 review

#36 Refactor: Post 관련 DTO 수정
  src/main/java/com/patientpal/backend/post/domain/Post.java
  src/main/java/com/patientpal/backend/post/dto/PostCreateRequest.java
  src/main/java/com/patientpal/backend/post/dto/PostCreateResponse.java
  src/main/java/com/patientpal/backend/post/dto/PostListResponse.java
  src/main/java/com/patientpal/backend/post/dto/PostResponse.java
  src/main/java/com/patientpal/backend/post/dto/PostUpdateRequest.java
Labels: 👀 review

#37 Feat: 두 필드가 서로 일치하는지 검증하는 @FieldMatch을 추가함
  src/main/java/com/patientpal/backend/common/validation/FieldMatchValidator.java
  src/main/java/com/patientpal/backend/common/validation/constraints/FieldMatch.java
  src/test/java/com/patientpal/backend/common/validation/FieldMatchValidatorTest.java
  src/test/java/com/patientpal/backend/fixtures/member/SignUpRequestFixture.java
Labels: ✨ feature, 👀 review
